version: '3.8'

services:
  backend:
    build: ./vision02-server
    container_name: vision-backend
    env_file:
      - ./.env
    volumes:
      - ./vision02-server:/app
    expose:
      - 8000
    networks:
      - app-network

  frontend:
    build:
      context: ./vision02-client/stop-ramen
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}

    container_name: vision-frontend
    env_file:
      - ./.env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge